query: '
  mutation unpinIssue($issueId: ID!){
    unpinIssue(input: { issueId: $issueId }) {
      issue {
        repository {
          id
        }
      }
    }
  }'
variables:
  issueId:
    type: jq
    file: pinnedIssues.json
    query: '.data.repository.pinnedIssues.nodes[]|{id: .issue.id, label: .issue.labels.nodes[].name}|if .label=="AWS" then .id else empty end'