name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: List Pinned Issues
      uses:  helaili/github-graphql-action@2.0.1
      id: listPinnedIssues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        query: .github/queries/pinnedissues.query.yaml
        accept: application/vnd.github.elektra-preview+json
        outputFile: pinnedIssues.json
    - name: Echo Report
      run: |
        echo ${{ steps.listPinnedIssues.outputs.queryResult }}
        echo ${{ env.GITHUB_EVENT_PATH }}
        cat ${{ env.GITHUB_EVENT_PATH }}
    - name: Unpin Issues
      uses: helaili/github-graphql-action@2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        query: .github/queries/unpinissue.query.yaml$
        accept: application/vnd.github.elektra-preview+json
    - name: AWS Ripper
      uses: ./ripper
      id: ripper
      with:
        AWSAccessKeyID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWSSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        defaultStopDelay: 21
        defaultTerminateDelay: 28
        dryRun: true
    - name: AWS Ripper Reporting
      uses: ./reporter 
      with:
        data: ${{ steps.ripper.outputs.report }}
        token: ${{ secrets.GITHUB_TOKEN }}
        label: AWS
    