name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: AWS Ripper
      uses: ./ripper
      id: ripper
      with:
        AWSAccessKeyID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWSSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        defaultStopDelay: 21
        defaultTerminateDelay: 28
        dryRun: true
    - name: Echo
      run: |
        echo ${{ steps.ripper.outputs.report }}
    - name: AWS Ripper Reporting
      uses: ./reporter 
      with:
        data: ${{ steps.ripper.outputs.report }}
    